version: "3.8"
services:
  hacker-news-server:
    image: hacker-news-server
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
        - 27017:27017
